# Generated by Django 4.2 on 2023-04-26 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('institution', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('issuance_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('student_id', models.CharField(blank=True, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentIdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='identity_cards/')),
                ('image_file', models.ImageField(upload_to='identity_cards/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idgenerator.student')),
            ],
        ),
    ]
