# Generated by Django 4.2 on 2023-04-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentidentitycard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='identity_cards/'),
        ),
        migrations.AlterField(
            model_name='studentidentitycard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='identity_cards/'),
        ),
    ]
